version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo-food-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8h7zspmfe8cd"
s3_prefix = "demo-food-api"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentName=\"Prod\""
